config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users
  resources :users, only: [:show, :index, :destroy]
  resources :charges, only: [:new, :create]
  resources :items
  resources :home, only: [:index]
  resources :carts, only: [:new, :show, :update]

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :users
  has_and_belongs_to_many :items

  def calc_cost
    cost = 0
    if items != nil
      items.each do |item|
        cost += item.price
      end
    end
    cost
  end
end

app/models/item.rb
class Item < ActiveRecord::Base

  has_attached_file :avatar, styles: { medium: "300x300>", fit: "100x100>" }

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates :name, :body, :price, presence: true
  belongs_to :user
  has_and_belongs_to_many :carts

  def self.most_recent
    order(created_at: :desc)[0..5]
  end

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items
  has_one :cart
  after_create :new_cart

  private
  def new_cart
    self.cart = Cart.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  rescue_from Pundit::NotDefinedError, with: :user_not_defined
  def is_admin?
    current_user && current_user.admin?
  end

  helper_method :is_admin?

private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

# Currently never being called, but persists as a saftey net for furture updates.
  def user_not_defined
    flash[:alert] = "You must sign in to do this."
    redirect_to(new_user_session_path)
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def new
    @item = Item.find(params[:item])
    @cart = current_user.cart
    @cart.items << @item
    flash[:notice] = "#{@item.name} Added to Cart"
    redirect_to cart_path(@cart)
  end

  def update
    @cart = current_user.cart
    @item = Item.find(params[:item])
    @cart.items.delete(@item)
    flash[:alert] = "#{@item.name} Deleted from Cart"
    redirect_to cart_path(@cart)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new

  end

  def create
    # Amount in cents
    @amount = (current_user.cart.calc_cost * 100).to_i

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )
    flash[:notice] = "Thank you for your purchase"
    current_user.cart = Cart.new
    redirect_to root_path
# Currently never being called, but persists as a saftey net for furture updates.
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to charges_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @items = Item.all
    @users = User.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  def index
    @items = Item.search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(per_page: 15, page: params[:page])
    authorize @items
  end

  def show
    authorize @item
  end

  def new
    @item = Item.new
    authorize @item
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    authorize @item
  end

  def update
    if @item.update(item_params)
      flash[:notice] = "Item updated!"
      redirect_to item_path(@item)
    else
      render :edit
    end
  end

  def destroy
    authorize @item
    @item.destroy
    @posts = Item.all
    redirect_to root_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :body, :price, :user_id, :avatar)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def sort_column
    Item.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w(asc desc).include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    authorize current_user
  end

  def show
    @user = User.find(params[:id])
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    authorize current_user
    @user.destroy
    redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
     title ||= column.titleize
     css_class = (column == sort_column) ? "current #{sort_direction}" : nil
     direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
     link_to title, params.merge(sort: column, direction: direction, page: nil), {class: css_class}
  end
end

app/views/carts/show.html.erb
<h1 class="page-header text-center">Your Cart</h1>
<% if current_user.cart.items.length == 0 %>
<h3>No Items Added to Cart</h3>
<% else %>
  <% current_user.cart.items.in_groups_of(3, false) do |item_group| %>
    <%= render "items/item_block", item_group: item_group %>
  <% end %>
<% end %>
<hr>
<h4>
  Total Cost: <%= number_to_currency(current_user.cart.calc_cost, unit: '$') %>
</h4>
<%= render template: "charges/new", item: @item %>
<br>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="<%= current_user.cart.items.length %> Items"
          data-amount="<%= (current_user.cart.calc_cost * 100).to_i %>"></script>
<% end %>

app/views/home/index.html.erb
<h1 class="page-header text-center">
  Welcome to Bit-Bizarre
  <p class="lead">
    The world's foremost bizarre goods storefront
  </p>
</h1>

<h3 class="text-center">Recently Added Items</h3>
<br>
<% if @items.any? %>
  <% @items.most_recent.in_groups_of(3, false) do |item_group| %>
    <%= render "items/item_block", item_group: item_group %>
  <% end %>
<% end %>

app/views/items/_form.html.erb
<%= render 'layouts/errors', object: @item %>

<%= bootstrap_form_for(@item) do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :body %>
  <%= f.number_field :price, step: '.01' %>
  <%= f.file_field :avatar %>
  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.submit data: {disable_with: 'S A V I N G'}, class: "btn btn-block" %>
<% end %>

app/views/items/_item_block.html.erb
<div class="row">
  <% item_group.each do |item| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading text-center"><%= link_to item.name, item_path(item) %></div>
        <div class="panel-body">
          <%= item.body %>
          <% if item.avatar_file_name != nil %>
            <%= image_tag item.avatar.url, class: "image-fit-to-panel img-rounded" %>
          <% end %>
        </div>
        <div class="panel-footer">
          <% if current_user && current_user.cart.items.include?(item) %>
            <%= link_to cart_path(current_user.cart, item: item), class: "btn btn-danger btn-block btn-sm", method: :patch do %>
              <span class="glyphicon glyphicon-shopping-cart"> Remove <%= number_to_currency(item.price, :unit => "$") %></span>
            <% end %>
          <% else %>
            <%= link_to new_cart_path(item: item), class: "btn btn-success btn-block btn-sm" do %>
              <span class="glyphicon glyphicon-shopping-cart"> Add <%= number_to_currency(item.price, :unit => "$") %></span>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/items/edit.html.erb
<%= render 'form' %>

app/views/items/index.html.erb
<h1>WELCOME 2 BITBIZARRE NEOPHYTE</h1>

<%= form_tag items_path, method: 'get' do %>
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", name: nil %>
<% end %>

<table class="table table-condensed">
  <thead>
    <th> <%= sortable "name" %></th>
    <th> <%= sortable "price" %></th>
    <th> <%= sortable "created_at" %></th>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.name, item_path(item) %></td>
        <td><%= number_to_currency(item.price, unit: "$") %></td>
        <td><i><%= "#{time_ago_in_words(item.created_at)} ago" %></i></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @items %>

<hr>
<% if current_user %>
  <%= link_to "New Item", new_item_path, class: "btn btn-info btn-block" %>
<% end %>
<br>

app/views/items/new.html.erb
<%= render 'form' %>

app/views/items/show.html.erb
<h3><%= @item.name %>
  <small class="muted green"><strong>- <%= number_to_currency(@item.price, unit: '$') %></strong></small>
  <span class="pull-right"> For sale by: <%= link_to @item.user.email, user_path(@item.user) %></span>
</h3>
  <% if is_admin? || current_user == @item.user %>
    <div class="btn-group text-center">
      <%= link_to 'Edit Item', edit_item_path(@item), class: "btn btn-warning" %>
      <%= link_to 'Delete Item', item_path(@item), method: :delete, class: "btn btn-danger" %>
    </div>
  <% end %>
<hr>

<p><%= @item.body %></p>
<% if @item.avatar_file_name != nil %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= image_tag @item.avatar.url(:medium), class: "img-responsive img-rounded" %>
    </div>
  </div>
<% end %>
<hr>
<% if current_user && current_user.cart.items.include?(@item) %>
  <%= link_to cart_path(current_user.cart, item: @item), class: "btn btn-danger btn-block btn-sm", method: :patch do %>
    <span class="glyphicon glyphicon-shopping-cart"> Remove <%= number_to_currency(@item.price, :unit => "$") %></span>
  <% end %>
<% else %>
  <%= link_to new_cart_path(item: @item), class: "btn btn-success btn-block btn-sm" do %>
    <span class="glyphicon glyphicon-shopping-cart"> Add <%= number_to_currency(@item.price, :unit => "$") %></span>
  <% end %>
<% end %>
<br>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>Please Fix the Following Errors:</h2>
    <h2><%= pluralize(object.errors.count, "error") %></h2>

    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BitBizarre</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png' %>
</head>
<body>

  <nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
      <a class="navbar-brand" href="/#">Home</a>
      <div class="navbar-collapse collapse">
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to 'Add Item', new_item_path %></li>
            <li><%= link_to 'Items', items_path %></li>
              <!-- Standard links go here -->
          </ul>
        <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="navbar-text">Logged in as <strong><%= link_to current_user.email, user_path(current_user) %></strong></li>
          <% if current_user && current_user.cart != nil %>
            <li><%= link_to "Cart #{number_to_currency(current_user.cart.calc_cost, unit: '$')}", cart_path(current_user.cart) %></li>
          <% end %>
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <div id="flash-notice">
    <% if flash[:notice] %>
      <div class="flash alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= flash[:notice] %>
      </div>
    <% end %>
  </div>

  <div id="flash-alert">
    <% if alert %>
      <div class="flash alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= flash[:alert] %>
      </div>
    <% end %>
  </div>

  <div class="container panel panel-master">
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/users/index.html.erb
<h1>All Users</h1>

<% if @users %>
  <table class="table">
    <thead>
      <tr>
        <th>Email</th>
        <% if is_admin? %>
          <th>Delete</th>
        <% end %>
      </tr>
    </thead>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.email, user_path(user) %></td>
        <td>
         <%= link_to user_path(user), data: {confirm: "Destroy User?", method: 'delete'}, id: "delete_user_#{user.id}" do %>
           <span class="glyphicon glyphicon-remove-sign red"></span>
         <% end %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/users/show.html.erb
<h1> <%= @user.email %></h1>

<% if @user.items.any? %>
  <% @user.items.in_groups_of(3, false) do |item_group| %>
    <%= render "items/item_block", item_group: item_group %>
  <% end %>
<% end %>

<% if is_admin? %>
  <%= link_to "Delete User", user_path(@user), data: {confirm: "Destroy User?", method: 'delete'}, class: "btn btn-danger btn-block" %>
<% end %>
<br>